version: '3.7'
services:
  java-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    container_name: java-api
    links:
      - mongo-db
    depends_on:
      - "mongo-db"    
  mongo-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
